// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1HVqw9naT6h3ddY8eJmMlMzoX8S7CaHM',
    appId: '1:740893627328:web:5b035e7d8f723ce0762e25',
    messagingSenderId: '740893627328',
    projectId: 'meqat-2b2e0',
    authDomain: 'meqat-2b2e0.firebaseapp.com',
    storageBucket: 'meqat-2b2e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhWilD7YtFiKsojuHsLkiw4jYMFhpU-xs',
    appId: '1:740893627328:android:0b248d65241d01af762e25',
    messagingSenderId: '740893627328',
    projectId: 'meqat-2b2e0',
    storageBucket: 'meqat-2b2e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkb7nTeT2FLGjGN3rtrMgqm5gADiIL2_I',
    appId: '1:740893627328:ios:1d1c242fdca8710c762e25',
    messagingSenderId: '740893627328',
    projectId: 'meqat-2b2e0',
    storageBucket: 'meqat-2b2e0.firebasestorage.app',
    iosBundleId: 'com.meqat.meqat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkb7nTeT2FLGjGN3rtrMgqm5gADiIL2_I',
    appId: '1:740893627328:ios:1d1c242fdca8710c762e25',
    messagingSenderId: '740893627328',
    projectId: 'meqat-2b2e0',
    storageBucket: 'meqat-2b2e0.firebasestorage.app',
    iosBundleId: 'com.meqat.meqat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1HVqw9naT6h3ddY8eJmMlMzoX8S7CaHM',
    appId: '1:740893627328:web:18faac66fdb9eb6a762e25',
    messagingSenderId: '740893627328',
    projectId: 'meqat-2b2e0',
    authDomain: 'meqat-2b2e0.firebaseapp.com',
    storageBucket: 'meqat-2b2e0.firebasestorage.app',
  );
}
