// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4bgrEcGmTaHBxBTd6EMSCGEWYyTE8sNI',
    appId: '1:986927910615:web:ada331ecba9ada3eff6a92',
    messagingSenderId: '986927910615',
    projectId: 'meqat-0001',
    authDomain: 'meqat-0001.firebaseapp.com',
    storageBucket: 'meqat-0001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArVWFCR_V5-6In9VBre5IAKnJSJf-SGo4',
    appId: '1:986927910615:android:f522bdb386027933ff6a92',
    messagingSenderId: '986927910615',
    projectId: 'meqat-0001',
    storageBucket: 'meqat-0001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYkC_c4O1LhdaNGuTIq6p7bQCLWBz7YW4',
    appId: '1:986927910615:ios:27307f9ca896de44ff6a92',
    messagingSenderId: '986927910615',
    projectId: 'meqat-0001',
    storageBucket: 'meqat-0001.firebasestorage.app',
    iosBundleId: 'com.meqat.meqat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYkC_c4O1LhdaNGuTIq6p7bQCLWBz7YW4',
    appId: '1:986927910615:ios:27307f9ca896de44ff6a92',
    messagingSenderId: '986927910615',
    projectId: 'meqat-0001',
    storageBucket: 'meqat-0001.firebasestorage.app',
    iosBundleId: 'com.meqat.meqat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4bgrEcGmTaHBxBTd6EMSCGEWYyTE8sNI',
    appId: '1:986927910615:web:7784114e529e7d57ff6a92',
    messagingSenderId: '986927910615',
    projectId: 'meqat-0001',
    authDomain: 'meqat-0001.firebaseapp.com',
    storageBucket: 'meqat-0001.firebasestorage.app',
  );

}